<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Navbar -->
    <Navbar />
    
    <!-- Main Content -->
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <!-- Back Button -->
      <div class="mb-6">
        <button 
          @click="goBack"
          class="flex items-center text-gray-600 hover:text-gray-800 transition-colors duration-200"
        >
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
          </svg>
          Back to Dashboard
        </button>
      </div>

      <!-- Box Info -->
      <div class="bg-white shadow-sm rounded-lg p-6 mb-6">
        <div class="flex justify-between items-start">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">{{ boxInfo.name }}</h1>
            <p class="text-gray-600 mt-1">Created by: {{ boxInfo.creator }}</p>
            <p class="text-gray-600">Current Code: <span class="font-mono font-bold text-blue-600">{{ boxInfo.currentCode }}</span></p>
          </div>
          <button 
            @click="regenerateCode"
            :disabled="regenerating"
            class="px-4 py-2 bg-blue-700 text-white rounded-lg hover:bg-gray-600 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center"
          >
            <svg v-if="regenerating" class="animate-spin -ml-1 mr-2 h-4 w-4 text-white" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
            {{ regenerating ? 'Regenerating...' : 'Regenerate Code' }}
          </button>
        </div>
      </div>

      <!-- History Section -->
      <div class="bg-white shadow-sm rounded-lg">
        <div class="px-6 py-4 border-b border-gray-200">
          <h2 class="text-xl font-semibold text-gray-900">Code History</h2>
        </div>

        <!-- Loading State -->
        <div v-if="loading" class="p-6 text-center">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mx-auto"></div>
          <p class="mt-2 text-gray-600">Loading history...</p>
        </div>

        <!-- Empty State -->
        <div v-else-if="history.length === 0" class="p-6 text-center text-gray-500">
          <svg class="w-12 h-12 mx-auto text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
          </svg>
          <p>No code history available.</p>
        </div>

        <!-- History List -->
        <div v-else class="divide-y divide-gray-200">
          <div 
            v-for="(record, index) in history" 
            :key="record.id"
            class="p-6 hover:bg-gray-50 transition-colors duration-200"
          >
            <div class="flex items-center justify-between">
              <!-- History Info -->
              <div class="flex-1">
                <div class="flex items-center space-x-3">
                  <span class="font-mono text-lg font-bold text-blue-600">{{ record.code }}</span>
                  <span 
                    v-if="index === 0"
                    class="px-2 py-1 text-xs font-medium bg-green-100 text-green-800 rounded-full"
                  >
                    Current
                  </span>
                </div>
                <div class="mt-2 space-y-1">
                  <p class="text-sm text-gray-600">
                    Generated by: <span class="font-medium">{{ record.generatedBy }}</span>
                  </p>
                  <p class="text-sm text-gray-500">
                    {{ formatDate(record.generatedAt) }}
                  </p>
                </div>
              </div>

              <!-- Action Icon -->
              <div class="flex items-center">
                <svg 
                  v-if="record.action === 'created'"
                  class="w-5 h-5 text-green-500"
                  fill="currentColor" 
                  viewBox="0 0 20 20"
                >
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                </svg>
                <svg 
                  v-else
                  class="w-5 h-5 text-blue-500"
                  fill="currentColor" 
                  viewBox="0 0 20 20"
                >
                  <path fill-rule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clip-rule="evenodd"></path>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Navbar from '@/components/Navbar.vue'

const route = useRoute()
const router = useRouter()

const boxId = ref(route.params.id)
const boxInfo = ref({})
const history = ref([])
const loading = ref(false)
const regenerating = ref(false)

const goBack = () => {
  router.push('/Dashbord')
}

const formatDate = (dateString) => {
  const date = new Date(dateString)
  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })
}

const fetchBoxHistory = async () => {
  loading.value = true
  try {
    // Mock data for frontend testing
    const mockBoxInfo = {
      id: boxId.value,
      name: `Box ${boxId.value === '1' ? 'Alpha' : boxId.value === '2' ? 'Beta' : 'Gamma'}`,
      creator: 'Alice Johnson',
      currentCode: `BOX${Math.floor(Math.random() * 9000) + 1000}`
    }
    
    const mockHistory = [
      {
        id: 1,
        code: mockBoxInfo.currentCode,
        generatedBy: 'Bob Smith',
        generatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'regenerated'
      },
      {
        id: 2,
        code: `BOX${Math.floor(Math.random() * 9000) + 1000}`,
        generatedBy: 'Charlie Brown',
        generatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'regenerated'
      },
      {
        id: 3,
        code: `BOX${Math.floor(Math.random() * 9000) + 1000}`,
        generatedBy: 'Alice Johnson',
        generatedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        action: 'created'
      }
    ]
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 800))
    
    boxInfo.value = mockBoxInfo
    history.value = mockHistory
    
    /*

    const response = await fetch(`/api/boxes/${boxId.value}/history`, {
      headers: {
        'Authorization': `Bearer ${localStorage.getItem('token')}`
      }
    })
    
    if (response.ok) {
      const data = await response.json()
      boxInfo.value = data.box
      history.value = data.history
    } else {
      console.error('Error fetching box history:', response.statusText)
    }
    */
  } catch (error) {
    console.error('Error fetching box history:', error)
  } finally {
    loading.value = false
  }
}

const regenerateCode = async () => {
  if (!confirm('Are you sure you want to regenerate the code for this box?')) {
    return
  }
  
  regenerating.value = true
  
  try {
    // Mock regeneration for frontend testing
    await new Promise(resolve => setTimeout(resolve, 1500))
    
    const newCode = `BOX${Math.floor(Math.random() * 9000) + 1000}`
    
    // Update current code
    boxInfo.value.currentCode = newCode
    
    // Add new record to history
    const newRecord = {
      id: Date.now(),
      code: newCode,
      generatedBy: 'John Doe', // Current user
      generatedAt: new Date().toISOString(),
      action: 'regenerated'
    }
    
    history.value.unshift(newRecord)
    
    /*
    const response = await fetch(`/api/boxes/${boxId.value}/regenerate`, {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${localStorage.getItem('token')}`
      }
    })
    
    if (response.ok) {
      const data = await response.json()
      boxInfo.value.currentCode = data.newCode
      
      // Add new record to history
      const newRecord = {
        id: data.historyId,
        code: data.newCode,
        generatedBy: data.generatedBy,
        generatedAt: data.generatedAt,
        action: 'regenerated'
      }
      
      history.value.unshift(newRecord)
    } else {
      console.error('Error regenerating code:', response.statusText)
      alert('Error regenerating code. Please try again.')
    }
    */
  } catch (error) {
    console.error('Error regenerating code:', error)
    alert('Error regenerating code. Please try again.')
  } finally {
    regenerating.value = false
  }
}

onMounted(() => {
  fetchBoxHistory()
})
</script>