<template>
  <div class="min-h-screen bg-gray-50">
    <!-- Navbar -->
    <Navbar />
    
    <!-- Main Content -->
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
      <!-- Back Button -->
      <div class="mb-6">
        <button 
          @click="goBack"
          class="flex items-center text-gray-600 hover:text-gray-800 transition-colors duration-200"
        >
          <svg class="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
          </svg>
          Back to Dashboard
        </button>
      </div>

      <!-- Error State -->
      <div v-if="error" class="bg-red-50 border border-red-200 rounded-lg p-6 mb-6">
        <div class="flex items-center">
          <svg class="w-5 h-5 text-red-400 mr-3" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clip-rule="evenodd"></path>
          </svg>
          <div>
            <h3 class="text-sm font-medium text-red-800">Error Loading History</h3>
            <p class="text-sm text-red-700 mt-1">{{ error }}</p>
          </div>
        </div>
        <button 
          @click="fetchBoxHistory"
          class="mt-4 px-4 py-2 bg-red-100 text-red-800 rounded-lg hover:bg-red-200 transition-colors duration-200"
        >
          Retry
        </button>
      </div>

      <!-- Box Info -->
      <div class="bg-white shadow-sm rounded-lg p-6 mb-6">
        <div class="flex justify-between items-start">
          <div>
            <h1 class="text-2xl font-bold text-gray-900">{{ boxInfo.name }}</h1>
            <p class="text-gray-600 mt-1">Created by: {{ boxInfo.creator }}</p>
            <p class="text-gray-600">Current Code: <span class="font-mono font-bold text-blue-600">{{ boxInfo.currentCode }}</span></p>
          </div>
        </div>
      </div>

      <!-- History Section -->
      <div class="bg-white shadow-sm rounded-lg">
        <div class="px-6 py-4 border-b border-gray-200">
          <h2 class="text-xl font-semibold text-gray-900">Code History</h2>
        </div>

        <!-- Loading State -->
        <div v-if="loading" class="p-6 text-center">
          <div class="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-500 mx-auto"></div>
          <p class="mt-2 text-gray-600">Loading history...</p>
        </div>

        <!-- Empty State -->
        <div v-else-if="history.length === 0" class="p-6 text-center text-gray-500">
          <svg class="w-12 h-12 mx-auto text-gray-400 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5H7a2 2 0 00-2 2v10a2 2 0 002 2h8a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"></path>
          </svg>
          <p>No code history available.</p>
        </div>

        <!-- History List -->
        <div v-else class="divide-y divide-gray-200">
          <div 
            v-for="(record, index) in history" 
            :key="record.id || index"
            class="p-6 hover:bg-gray-50 transition-colors duration-200"
          >
            <div class="flex items-center justify-between">
              <!-- History Info -->
              <div class="flex-1">
                <div class="flex items-center space-x-3">
                  <span class="font-mono text-lg font-bold text-blue-600">{{ record.code }}</span>
                  <span 
                    v-if="index === 0"
                    class="px-2 py-1 text-xs font-medium bg-green-100 text-green-800 rounded-full"
                  >
                    Current
                  </span>
                </div>
                <div class="mt-2 space-y-1">
                  <p class="text-sm text-gray-600">
                    Generated by: <span class="font-medium">{{ record.generated_by }}</span>
                  </p>
                  <p class="text-sm text-gray-500">
                    {{ formatDate(record.generated_at) }}
                  </p>
                </div>
              </div>

              <!-- Action Icon -->
              <div class="flex items-center">
                <svg 
                  v-if="index === history.length - 1"
                  class="w-5 h-5 text-green-500"
                  fill="currentColor" 
                  viewBox="0 0 20 20"
                >
                  <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path>
                </svg>
                <svg 
                  v-else
                  class="w-5 h-5 text-blue-500"
                  fill="currentColor" 
                  viewBox="0 0 20 20"
                >
                  <path fill-rule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clip-rule="evenodd"></path>
                </svg>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import Navbar from '@/components/Navbar.vue'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const boxId = ref(route.params.id)
const boxInfo = ref({})
const history = ref([])
const loading = ref(false)
const regenerating = ref(false)
const error = ref('')

// Helper function to check authentication
const checkAuth = () => {
  if (!authStore.user || !authStore.token) {
    alert('Session expired. Please login again.')
    authStore.logout()
    router.push('/Login')
    return false
  }
  return true
}

const goBack = () => {
  router.push('/Dashbord')
}

const formatDate = (dateString) => {
  try {
    const date = new Date(dateString)
    return date.toLocaleString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    })
  } catch (err) {
    return dateString
  }
}

const fetchBoxHistory = async () => {
  if (!checkAuth()) return
  
  loading.value = true
  error.value = ''
  
  try {
    // First, fetch box info from the main boxes endpoint
    const boxResponse = await fetch(`http://localhost:8000/api/coffres`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    
    if (!boxResponse.ok) {
      throw new Error('Failed to fetch box information')
    }
    
    const boxData = await boxResponse.json()
    const currentBox = boxData.coffres.find(box => box.id === parseInt(boxId.value))
    
    if (!currentBox) {
      throw new Error('Box not found')
    }
    
    // Set box info
    boxInfo.value = {
      id: currentBox.id,
      name: currentBox.name,
      creator: currentBox.owner,
      currentCode: currentBox.current_code
    }
    
    // Then fetch the history
    const historyResponse = await fetch(`http://localhost:8000/api/coffres/${boxId.value}/history`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    
    if (!historyResponse.ok) {
      if (historyResponse.status === 401) {
        await authStore.logout()
        router.push('/Login')
        return
      }
      if (historyResponse.status === 403) {
        throw new Error('You are not authorized to view this box history')
      }
      if (historyResponse.status === 404) {
        throw new Error('Box not found')
      }
      throw new Error(`Failed to fetch history: ${historyResponse.status}`)
    }
    
    const historyData = await historyResponse.json()
    
    // Sort history by date (newest first) to ensure current code is at the top
    history.value = historyData.sort((a, b) => new Date(b.generated_at) - new Date(a.generated_at))
    
  } catch (err) {
    console.error('Error fetching box history:', err)
    error.value = err.message || 'Failed to fetch box history'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  if (!boxId.value) {
    error.value = 'Box ID is required'
    return
  }
  fetchBoxHistory()
})
</script>